name: Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'

jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh

      - name: Check new patch ReVanced
        id: check-rv
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh ReVanced/revanced-patches latest youtube-revanced.apk

      - name: Check new patch Revanced Extended forked by Anddea Stable Version
        id: check-rve-anddea-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches latest youtube-stable-anddea.apk

      - name: Check new patch Revanced Extended forked by Anddea Beta Version
        id: check-rve-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease youtube-beta-anddea.apk

      - name: Check new patch Twitter Piko Stable
        id: check-twitter-piko-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko latest twitter-stable-piko.apk

      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko prerelease twitter-beta-piko.apk

      - name: Re-run workflow if github connection not stable
        if: always() && steps.check-rv.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: actions/github-script@v7
        with:
          script: |
            const maxRetries = ${{ env.max_retries }};
            let retryCount = ${{ env.retry_count }};
            if (retryCount < maxRetries) {
              retryCount += 1;
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "ci.yml",
                ref: context.ref,
                inputs: {
                  'retry_count': String(retryCount)
                }
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          retry_count: ${{ github.event.inputs.retry_count }}
          max_retries: 3

    outputs:
      check_rv: ${{ steps.check-rv.outputs.new_patch }}
      check_rve_anddea_stable: ${{ steps.check-rve-anddea-stable.outputs.new_patch }}
      check_rve_anddea_beta: ${{ steps.check-rve-anddea-beta.outputs.new_patch }}
      check_twitter_piko_stable: ${{ steps.check-twitter-piko-stable.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}

  Patch-Revanced:
    name: Patch Revanced Stable
    needs: check
    if: ${{ needs.check.outputs.check_rv == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced"

  Patch-RVE-anddea-stable:
    name: Patch RVX Anddea Stable
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-stable"

  Patch-RVE-anddea-beta:
    name: Patch RVX Anddea Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-beta"

  Patch-Twitter-Piko-Stable:
    name: Patch Twitter Piko Stable
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Stable"

  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"
